{{- if .Values.image.registryConfigJSON  }}
{{- $registry := .Values.image.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-kac.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}