apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "falcon-kac.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'