{{- if not .Values.crowdstrikeConfig.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
data:
  AGENT_CLIENT_ID: {{ .Values.crowdstrikeConfig.clientID | b64enc | quote }}
  AGENT_CLIENT_SECRET: {{ .Values.crowdstrikeConfig.clientSecret | b64enc | quote }}
{{- end }}
