apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cs-k8s-protection-agent.fullname" . }}
  labels:
  {{- include "cs-k8s-protection-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - batch
    resources:
    - cronjobs
    - jobs
    verbs:
    - watch
    - list
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    - ingresses
    verbs:
    - watch
    - list
  - apiGroups:
    - apps
    - extensions
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    verbs:
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - nodes
    - pods
    - services
    verbs:
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
    verbs:
    - get
    - list
    - watch
