{{ if or (.Values.crowdstrikeConfig.dockerAPIToken) (.Values.image.registryConfigJSON) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cs-k8s-protection-agent.fullname" . }}-regsecret
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cs-k8s-protection-agent.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{- if .Values.crowdstrikeConfig.dockerAPIToken }}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- if .Values.image.registryConfigJSON }}
  .dockerconfigjson: {{ .Values.image.registryConfigJSON }}
{{- end }}
{{- end}}
